### ISSUE TITLE
Serialization issue

### ISSUE THREAD

**Issue by edgBR** [StatMixedML/XGBoostLSS#17] opened 2022-06-01 12:09 UTC
Dear Alexander,

We are now comparing MAPIE confidence intervals to a custom methodology we have created based on the XGBoostLSS. 

Basically we are using the expectiles that XGBoostLSS provides us to fit a CDF that is an approximation to a tweedie CDF. (This is a bit hacky but we are getting theoretical coverage).

The problem is that we are splitting this procedure in 2 parts and we are using the joblib of XGBoostLSS to the input of the CDF approximation process.

I have not seen any example of how to serialize XGBoostLSS objects but when trying with joblib:

```python
        X_train_ci = processor_reg.transform(regression_df.drop(columns=[arguments.clf_targets] +
                                                                                [arguments.reg_targets])) 
        y_train_ci = regression_df[arguments.reg_targets]
        n_cpu = multiprocessing.cpu_count()
        dtrain = xgb.DMatrix(X_train_ci, label=y_train_ci, nthread=n_cpu)

        logging.info("Training XGBoost")
        xgboostlss_model_expectile = xgboostlss.train(hyperparameters,
                                                      dtrain,
                                                      dist=distribution_expectile,
                                                      num_boost_round=hyperparameters["opt_rounds"],
                                                      verbose_eval=True)
        
        if partial:
            logging.info("Serializing partial fit")
            joblib.dump(xgboostlss_model_expectile, 'outputs/models/zip_conf_partial_fit.joblib')
        else:
            logging.info("Serializing full fit")
            joblib.dump(xgboostlss_model_expectile, 'outputs/models/zip_conf.joblib')
```

We are getting the following error:

![image](https://user-images.githubusercontent.com/14976422/171400757-df70fcb3-9aac-4570-8d0d-0ac32f27c1d0.png)

Being distribution expectile defined as:

```python
        distribution_expectile = Expectile                                   
        distribution_expectile.expectiles =  arguments.exp_list
        distribution_expectile.stabilize = "MAD" 
```

Are we choosing the wrong serialization method? Do we need to save XGBoostLSS in a different way?

BR
Edgar

**Comment by StatMixedML** [comment] 2022-06-01 17:37
@edgBR Thanks for raising the issue.

It seems like the problem is with the [starting values](https://github.com/StatMixedML/XGBoostLSS/blob/master/xgboostlss/distributions/Expectile.py#L74).

Does the problem occur for the predict function only or also during model training?

**Comment by edgBR** [comment] 2022-06-02 07:10
Hi @StatMixedML 

This only happens when I save the model as joblib and I load it again to make predictions.

When training and predicting within the same session/notebook etc... Everything works as expected.

Unfortunately I do not see how ray can help here. Do you have an example where you save the model and load it again to make predictions?

BR
Edgar

**Comment by edgBR** [comment] 2022-06-02 11:22
Ey,

Yes, please find attached:


```python
!pip install git+https://github.com/StatMixedML/XGBoostLSS.git
import numpy as np
import pandas as pd
import pkg_resources
import itertools
import shap 
import math
import multiprocessing
from scipy.stats import norm
import matplotlib.pyplot as plt
import plotnine
from plotnine import *
plotnine.options.figure_size = (20, 10)

from xgboostlss.model import *
from xgboostlss.distributions.Expectile import Expectile
from xgboostlss.datasets.data_loader import load_simulated_data

# The data is a simulated Gaussian as follows, where x is the only true feature and all others are noise variables
    # loc = 10
    # scale = 1 + 4*((0.3 < x) & (x < 0.5)) + 2*(x > 0.7)

train, test = load_simulated_data()
n_cpu = multiprocessing.cpu_count()

X_train, y_train = train.iloc[:,1:],train.iloc[:,0]
X_test, y_test = test.iloc[:,1:],test.iloc[:,0]

dtrain = xgb.DMatrix(X_train, label=y_train, nthread=n_cpu)
dtest = xgb.DMatrix(X_test, nthread=n_cpu)


np.random.seed(123)

n_rounds = opt_params["opt_rounds"]
del opt_params["opt_rounds"]

# Train Model with optimized hyper-parameters
xgboostlss_model = xgboostlss.train(opt_params,
                                    dtrain,
                                    dist=distribution,
                                    num_boost_round=n_rounds)

import joblib
joblib.dump(xgboostlss_model, 'my_model.joblib')

```

Now we close our session and we restart a new one and we run:
```

import numpy as np
import pandas as pd
import pkg_resources
import itertools
import shap 
import math
import multiprocessing
from scipy.stats import norm
import matplotlib.pyplot as plt
import plotnine
from plotnine import *
plotnine.options.figure_size = (20, 10)

from xgboostlss.model import *
from xgboostlss.distributions.Expectile import Expectile
from xgboostlss.datasets.data_loader import load_simulated_data

# The data is a simulated Gaussian as follows, where x is the only true feature and all others are noise variables
    # loc = 10
    # scale = 1 + 4*((0.3 < x) & (x < 0.5)) + 2*(x > 0.7)

train, test = load_simulated_data()
n_cpu = multiprocessing.cpu_count()

X_train, y_train = train.iloc[:,1:],train.iloc[:,0]
X_test, y_test = test.iloc[:,1:],test.iloc[:,0]

dtrain = xgb.DMatrix(X_train, label=y_train, nthread=n_cpu)
dtest = xgb.DMatrix(X_test, nthread=n_cpu)

distribution = Expectile  
distribution.expectiles = [0.05, 0.95]     # Expectiles to be estimated: needs to be a list of at least two expectiles.
distribution.stabilize = "MAD"       

my_model= joblib.load('my_model.joblib')

predictions = xgboostlss.predict(xgboostlss_model, 
                                    dtest, 
                                    dist=distribution,
                                    pred_type="expectiles")
```


```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-10-61103a19a665>](https://localhost:8080/#) in <module>()
      2                                     dtest,
      3                                     dist=distribution,
----> 4                                     pred_type="expectiles")

[/usr/local/lib/python3.7/dist-packages/xgboostlss/model.py](https://localhost:8080/#) in predict(booster, dtest, dist, pred_type, n_samples, quantiles, seed)
    330 
    331         # Set base_margin as starting point for each distributional parameter. Requires base_score=0 in parameters.
--> 332         base_margin = (np.ones(shape=(dtest.num_row(), 1))) * dist.start_values
    333         dtest.set_base_margin(base_margin.flatten())
    334 
AttributeError: type object 'Expectile' has no attribute 'start_values'
```

Looking to the code we are trying now to initialize the start values as:

`distribution.start_values = [np.mean(target_train), np.mean(target_train)]`

But we are wondering if this is the right way.

**Comment by StatMixedML** [comment] 2022-06-02 13:08
@edgBR The following fixes the problem

```python
import numpy as np
import pandas as pd
import pkg_resources
import itertools
import shap 
import math
import multiprocessing
from scipy.stats import norm
import matplotlib.pyplot as plt
import joblib
import plotnine
from plotnine import *
plotnine.options.figure_size = (20, 10)

from xgboostlss.model import *
from xgboostlss.distributions.Expectile import Expectile
from xgboostlss.datasets.data_loader import load_simulated_data

# The data is a simulated Gaussian as follows, where x is the only true feature and all others are noise variables
    # loc = 10
    # scale = 1 + 4*((0.3 < x) & (x < 0.5)) + 2*(x > 0.7)

train, test = load_simulated_data()
n_cpu = multiprocessing.cpu_count()

X_train, y_train = train.iloc[:,1:],train.iloc[:,0]
X_test, y_test = test.iloc[:,1:],test.iloc[:,0]

dtrain = xgb.DMatrix(X_train, label=y_train, nthread=n_cpu)
dtest = xgb.DMatrix(X_test, nthread=n_cpu)

distribution = Expectile  
distribution.expectiles = [0.05, 0.95]     # Expectiles to be estimated: needs to be a list of at least two expectiles.
distribution.stabilize = "MAD"   
distribution.start_values = distribution.initialize(dtrain.get_label())

xgboostlss_model= joblib.load('my_model.joblib')

predictions = xgboostlss.predict(xgboostlss_model, 
                                 dtest, 
                                 dist=distribution,
                                 pred_type="expectiles")
predictions.head()
```
The only thing I changed, compared to your suggestion, is `distribution.start_values = distribution.initialize(dtrain.get_label())
`. The issue stems from [this](https://github.com/StatMixedML/XGBoostLSS/blob/master/xgboostlss/model.py#L85), i.e., starting values are initialized during model training only, and hence not available after you re-load the  model. Hence, since you load the trained model, [this](https://github.com/StatMixedML/XGBoostLSS/blob/master/xgboostlss/model.py#L332) causes the problem, since `dist.start_values` are not initialized since model training is already done in the prior step.

Hope this solves the problem to some extent. If you have som suggestion on how to better pass the starting values to the model let me know.

**Comment by edgBR** [comment] 2022-06-02 14:24
Hi,

This works but this is very hacky imho. My suggestion would be to not return a booster object in xgboostlss.train. Instead we can return a custom class where inside the self we have the booster and also the distribution object.

What do you think?

**Comment by StatMixedML** [comment] 2022-06-02 17:31
@edgBR Having a dedicated XGBoostLSS class is also my preferred option. Yet, I haven't had time to do that...

**Comment by StatMixedML** [comment] 2022-06-05 08:18
Closing the issue for now, using the interim solution.

**Closed by StatMixedML** 2022-06-05 08:18 UTC
